# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  message:  # id of input
    description: 'Who to greet'
    required: true
    default: 'Code coverage'
  gist_id:
    default: '9a9cd8f729d7d20be9d383d11ccbf3df'
  color:
    default: 'red'
  value:
    default: 35
  secret:
    required: True
  filename:
    default: 'coverage.json'
  user:
    required: True
runs:
  using: 'docker'
  image: 'Dockerfile'
