# action.yml
name: 'Action for dynamic badges'
description: 'Create dynamic badge to be displayed in the README.md file'
inputs:
  message: 
    description: 'Message of the badge'
    required: true
    default: 'Code coverage'
  gist_id:
    required: true
    default: ''
  color:
    default: 'red'
  value:
    default: 35
  secret:
    required: True
  filename:
    default: 'coverage.json'
  user:
    required: True
runs:
  using: 'docker'
  image: 'Dockerfile'
